version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./home/docker_databases:/var/lib/postgresql
    environment:
      - POSTGRES_DB=DDTmetod
      - POSTGRES_USER=DDTmetod
      - POSTGRES_PASSWORD=1234
    ports:
    - 5431:5432