# Generated by Django 3.2 on 2021-04-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210418_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'Районы'},
        ),
        migrations.AlterModelOptions(
            name='organizationmetod',
            options={'verbose_name': 'Организации методистов'},
        ),
        migrations.AlterModelOptions(
            name='regulations',
            options={'verbose_name': 'Нормативно правовые акты'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Персонал'},
        ),
        migrations.AlterModelOptions(
            name='staffcategory',
            options={'verbose_name': 'Категории персонала'},
        ),
        migrations.AlterModelOptions(
            name='udo',
            options={'verbose_name': 'Учреждения дошкольного образования'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь'},
        ),
        migrations.AlterField(
            model_name='staff',
            name='type',
            field=models.IntegerField(choices=[(0, 'Количественный состав'), (1, 'Постоянные, совместители'), (2, 'Квалификационный ценз'), (3, 'Образовательный ценз')], verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(max_length=255, verbose_name='Должность'),
        ),
    ]
