# Generated by Django 3.2 on 2021-04-22 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210420_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnionInteresProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Профили для объединений по интересам',
                'verbose_name_plural': 'Профили для объединений по интересам',
            },
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'Районы', 'verbose_name_plural': 'Районы'},
        ),
        migrations.AlterModelOptions(
            name='organizationmetod',
            options={'verbose_name': 'Организации методистов', 'verbose_name_plural': 'Организации методистов'},
        ),
        migrations.AlterModelOptions(
            name='regulations',
            options={'verbose_name': 'Нормативно правовые акты', 'verbose_name_plural': 'Нормативно правовые акты'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Персонал', 'verbose_name_plural': 'Персонал'},
        ),
        migrations.AlterModelOptions(
            name='staffcategory',
            options={'verbose_name': 'Категории персонала', 'verbose_name_plural': 'Категории персонала'},
        ),
        migrations.AlterModelOptions(
            name='udo',
            options={'verbose_name': 'Учреждения дошкольного образования', 'verbose_name_plural': 'Учреждения дошкольного образования'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователь'},
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.CreateModel(
            name='UnionInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Количественный состав'), (1, 'Постоянные, совместители'), (2, 'Квалификационный ценз'), (3, 'Образовательный ценз')], verbose_name='Тип')),
                ('group_value', models.PositiveIntegerField(verbose_name='Количество групп')),
                ('people_value', models.PositiveIntegerField(verbose_name='Количество людей')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unioninteresprofile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Объединения по интересам',
                'verbose_name_plural': 'Объединения по интересам',
            },
        ),
    ]
