# Generated by Django 3.2 on 2021-05-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210422_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to='npa', verbose_name='Файл')),
            ],
        ),
    ]
