# Generated by Django 3.2 on 2021-05-07 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_npa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NPA',
        ),
    ]
