# Generated by Django 3.2 on 2021-05-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_npa'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to='metodic_events/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Методические мероприятия',
                'verbose_name_plural': 'Методические мероприятия',
            },
        ),
    ]
