# Generated by Django 3.2 on 2021-05-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_metodicevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.IntegerField(choices=[(1, 'Житковичи'), (2, 'Петриков'), (3, 'Октябрьский'), (4, 'Светлогорск'), (5, 'Жлобин'), (6, 'Рогачев'), (7, 'Корма'), (8, 'Чечерск'), (9, 'Ветка'), (10, 'Буда-кошелево'), (11, 'Добруш'), (12, 'Гомель'), (13, 'Речица'), (14, 'Лоев'), (15, 'Брагин'), (16, 'Хойники'), (17, 'Калинковичи'), (18, 'Наровля'), (19, 'Мозырь'), (20, 'Ельск'), (21, 'Лельчицы')], verbose_name='Название'),
        ),
    ]
