# Generated by Django 3.2 on 2021-05-23 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210511_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcategory',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.staff', verbose_name='Персонал'),
        ),
        migrations.AlterField(
            model_name='staffcategory',
            name='value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='udo',
            name='district',
            field=models.IntegerField(choices=[(1, 'Житковичский район'), (2, 'Петриковский район'), (3, 'Октябрьский район'), (4, 'Светлогорский район'), (5, 'Жлобинский район'), (6, 'Рогачевский район'), (7, 'Кормянский район'), (8, 'Чечерский район'), (9, 'Ветковский район'), (10, 'Буда-Кошелёвский район'), (11, 'Добрушский район'), (12, 'Гомельский район'), (13, 'Речицкий район'), (14, 'Лоевский район'), (15, 'Брагинский район'), (16, 'Хойникский район'), (17, 'Калинковичский район'), (18, 'Наровлянский район'), (19, 'Мозырский район'), (20, 'Ельский район'), (21, 'Лельчицкий район'), (22, 'г. Гомель')], verbose_name='Район'),
        ),
    ]
